pins:
  - pin: A4
    function: Power GND
    type: gnd

info:
  cid: Honda-OBD2A
  title: Hellen OBD2A
  name: Hellen OBD2A
  directory: hellen/hellen-honda-obd2a
  image:
    file: honda-obd2.jpg
  pins:
    - pin: A2
      x: 85
      y: 85
