name: Generate Interactive BOMs

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Checkout Submodules
      run: |
        git submodule update --init --depth=1 hardware/InteractiveHtmlBom

    - name: Install prerequisite software
      run: |
        sudo bash misc/actions/add-ubuntu-latest-apt-mirrors.sh
        sudo add-apt-repository --yes ppa:kicad/kicad-7.0-releases
        sudo apt-get install kicad sshpass

    - name: Set SSH variables
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      run: |
        if [ "${{github.ref}}" = "refs/heads/master" ]; then
          echo "gerefi_SSH_SERVER=${{secrets.gerefi_SSH_SERVER}}" >> $GITHUB_ENV
          echo "gerefi_SSH_USER=${{secrets.gerefi_SSH_USER}}" >> $GITHUB_ENV
          echo "gerefi_SSH_PASS=${{secrets.gerefi_SSH_PASS}}" >> $GITHUB_ENV
        fi

    - name: Generate documentation
      env:
        INTERACTIVE_HTML_BOM_NO_DISPLAY: 'true'
      run: bash ./misc/jenkins/generate_ibom/gen_upload_ibom.sh
