name: Generate firmware Doxygen

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install prerequisite software
      run: |
        sudo bash misc/actions/add-ubuntu-latest-apt-mirrors.sh
        sudo apt-get install doxygen graphviz sshpass

    - name: Set FTP variables
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      run: |
        if [ "${{github.ref}}" = "refs/heads/master" ]; then
          echo "gerefi_SSH_SERVER=${{secrets.gerefi_SSH_SERVER}}" >> $GITHUB_ENV
          echo "gerefi_SSH_USER=${{secrets.gerefi_SSH_USER}}" >> $GITHUB_ENV
          echo "gerefi_SSH_PASS=${{secrets.gerefi_SSH_PASS}}" >> $GITHUB_ENV
        fi

    - name: Generate documentation
      run: bash ./misc/jenkins/generate_doxygen/gen_upload_docs.sh
